const SEED_MEMBERS = [
  { team_id: 1, name: 'Alex', role: 'Tesoureiro', phone: '64999077331', email: 'buttielle3@gmail.com' },
  { team_id: 20, name: 'João Teste', role: 'Membro', phone: '1199999', email: 'test@test.com' },
  { team_id: 5, name: 'Eduardo', role: 'Vice encarregado', phone: '', email: '' },
  { team_id: 5, name: 'Fernanda ', role: 'Encarregada', phone: '', email: '' },
  { team_id: 5, name: 'Vitoria', role: 'Auxiliar', phone: '', email: '' },
  { team_id: 5, name: 'Fred', role: 'Cozinheiro', phone: '', email: '' },
  { team_id: 5, name: 'Monyque', role: 'Auxiliar', phone: '', email: '' },
  { team_id: 5, name: 'Victor', role: 'Auxiliar', phone: '', email: '' },
  { team_id: 5, name: 'Matheus ', role: 'Auxiliar', phone: '', email: '' },
  { team_id: 5, name: 'Leticia', role: 'Auxiliar', phone: '', email: '' },
  { team_id: 5, name: 'Verinha ', role: 'Cozinheira', phone: '', email: '' },
  { team_id: 6, name: 'Adryelle', role: 'Dina', phone: '', email: '' },
  { team_id: 6, name: 'Rafaela', role: 'Dina', phone: '', email: '' },
  { team_id: 6, name: 'José Gabriel', role: 'Dina', phone: '', email: '' },
  { team_id: 6, name: 'Leonardo', role: 'Encarregado', phone: '', email: '' },
  { team_id: 6, name: 'Laura', role: 'Dina', phone: '', email: '' },
  { team_id: 6, name: 'Daniel', role: 'Dina', phone: '', email: '' },
  { team_id: 3, name: 'Samuel', role: '', phone: '', email: '' },
  { team_id: 3, name: 'Mamuty', role: '', phone: '', email: '' },
  { team_id: 19, name: 'Bruno Alves', role: 'Operário', phone: '', email: '' },
  { team_id: 19, name: 'Daiane', role: 'Operário', phone: '', email: '' },
  { team_id: 19, name: 'Vagner Nunes', role: 'Operário', phone: '', email: '' },
  { team_id: 19, name: 'Ir. Edson', role: 'Operário', phone: '', email: '' },
  { team_id: 19, name: 'Manuela Guia', role: 'Operário', phone: '', email: '' },
  { team_id: 12, name: 'Juliano', role: 'Operário', phone: '', email: '' },
  { team_id: 12, name: 'João Gabriel', role: 'Operário', phone: '', email: '' },
  { team_id: 4, name: 'Thaís', role: 'Operário', phone: '', email: '' },
  { team_id: 4, name: 'Maria Eduarda Vieira', role: 'Operário', phone: '', email: '' },
  { team_id: 18, name: 'Laianne', role: 'Operário', phone: '', email: '' },
  { team_id: 18, name: 'Lilian', role: 'Operário', phone: '', email: '' },
  { team_id: 18, name: 'Carolzinha', role: 'Operário', phone: '', email: '' },
  { team_id: 18, name: 'Luciana', role: 'Operário', phone: '', email: '' },
  { team_id: 18, name: 'Rafael', role: 'Operário', phone: '', email: '' },
  { team_id: 18, name: 'Zezão', role: 'Operário', phone: '', email: '' },
  { team_id: 9, name: 'Maria Eduarda da Silva Oliveira', role: 'Operário', phone: '', email: '' },
  { team_id: 9, name: 'Maria Eduarda Gomes', role: 'Operário', phone: '', email: '' },
  { team_id: 9, name: 'José Mário', role: 'Operário', phone: '', email: '' },
  { team_id: 9, name: 'Yohana', role: 'Operário', phone: '', email: '' },
  { team_id: 9, name: 'Geovana Souza', role: 'Operário', phone: '', email: '' },
  { team_id: 9, name: 'Lucas Arruda', role: 'Operário', phone: '', email: '' },
  { team_id: 9, name: 'Dhiogo Ciganin', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Rebeca', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Marília', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Daniele', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Maria Antônia', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Isabela Nascimento', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Geovana Sousa', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Elias', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Sávio', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Raysla', role: 'Operário', phone: '', email: '' },
  { team_id: 3, name: 'Ana Luiza Vilaça', role: 'Operário', phone: '', email: '' },
  { team_id: 3, name: 'Maria Eduarda Souza', role: 'Operário', phone: '', email: '' },
  { team_id: 3, name: 'João Pedro', role: 'Operário', phone: '', email: '' },
  { team_id: 3, name: 'Maria das Graças', role: 'Operário', phone: '', email: '' },
  { team_id: 3, name: 'Maria Eduarda Silva', role: 'Operário', phone: '', email: '' },
  { team_id: 3, name: 'Maria Fernanda', role: 'Operário', phone: '', email: '' },
  { team_id: 11, name: 'João Alvarenga', role: 'Operário', phone: '', email: '' },
  { team_id: 11, name: 'Isabella Vaz', role: 'Operário', phone: '', email: '' },
  { team_id: 11, name: 'Ayan', role: 'Operário', phone: '', email: '' },
  { team_id: 11, name: 'Rafaela (Cenáculo)', role: 'Operário', phone: '', email: '' },
  { team_id: 11, name: 'Gustavo de Lima (Cenáculo)', role: 'Operário', phone: '', email: '' },
  { team_id: 7, name: 'Ana Beatriz', role: 'Operário', phone: '', email: '' },
  { team_id: 7, name: 'Élen', role: 'Operário', phone: '', email: '' },
  { team_id: 7, name: 'Isadora Ferreira (Cenáculo)', role: 'Operário', phone: '', email: '' },
  { team_id: 7, name: 'Washington', role: 'Operário', phone: '', email: '' },
  { team_id: 10, name: 'Aisla', role: 'Operário', phone: '', email: '' },
  { team_id: 10, name: 'Gabriela', role: 'Operário', phone: '', email: '' },
  { team_id: 10, name: 'Luana', role: 'Operário', phone: '', email: '' },
  { team_id: 10, name: 'Matheus', role: 'Operário', phone: '', email: '' },
  { team_id: 10, name: 'Murilo', role: 'Operário', phone: '', email: '' },
  { team_id: 10, name: 'Edimárcio', role: 'Operário', phone: '', email: '' },
  { team_id: 5, name: 'Fernanda', role: 'Operário', phone: '', email: '' },
  { team_id: 5, name: 'Letícia', role: 'Operário', phone: '', email: '' },
  { team_id: 5, name: 'Matheus', role: 'Operário', phone: '', email: '' },
  { team_id: 5, name: 'Malu', role: 'Operário', phone: '', email: '' },
  { team_id: 13, name: 'Amanda', role: 'Operário', phone: '', email: '' },
  { team_id: 13, name: 'Maryanna', role: 'Operário', phone: '', email: '' },
  { team_id: 13, name: 'Almir', role: 'Operário', phone: '', email: '' },
  { team_id: 13, name: 'Milena', role: 'Operário', phone: '', email: '' },
  { team_id: 13, name: 'Reis', role: 'Operário', phone: '', email: '' },
  { team_id: 13, name: 'Dantas', role: 'Operário', phone: '', email: '' },
  { team_id: 13, name: 'Yan Caetano', role: 'Operário', phone: '', email: '' },
  { team_id: 8, name: 'Carla', role: 'Operário', phone: '', email: '' },
  { team_id: 8, name: 'Nathaly', role: 'Operário', phone: '', email: '' },
  { team_id: 8, name: 'Lucas Piassi', role: 'Operário', phone: '', email: '' },
  { team_id: 8, name: 'Kelio', role: 'Operário', phone: '', email: '' },
  { team_id: 8, name: 'Sophia', role: 'Operário', phone: '', email: '' },
  { team_id: 14, name: 'Hetfield', role: 'Operário', phone: '', email: '' },
  { team_id: 14, name: 'Júlia Piassi', role: 'Operário', phone: '', email: '' },
  { team_id: 15, name: 'Lucas Quiel', role: 'Operário', phone: '', email: '' },
  { team_id: 7, name: 'Washigton', role: 'Operário', phone: '', email: '' },
  { team_id: 10, name: 'Edimárcio (Sonorização e laboral)', role: 'Operário', phone: '', email: '' },
  { team_id: 16, name: 'Waliison', role: 'Operário', phone: '', email: '' },
  { team_id: 6, name: 'Pedro André', role: 'Operário', phone: '', email: '' },
  { team_id: 6, name: 'Laura Nascimento', role: 'Operário', phone: '', email: '' },
  { team_id: 6, name: 'Rafaela bueno', role: 'Operário', phone: '', email: '' },
  { team_id: 1, name: 'Juliana ', role: 'Relações Públicas', phone: '', email: '' },
  { team_id: 1, name: 'Johnny ', role: 'Condutor', phone: '', email: '' },
  { team_id: 1, name: 'Aparecida', role: 'Secretaria', phone: '', email: '' },
  { team_id: 2, name: 'Geovanna', role: 'Supervisora In loko', phone: '', email: '' },
  { team_id: 2, name: 'Raphael', role: 'Supervisor Extra', phone: '', email: '' },
];

module.exports = {
  up(db) {
    const existing = db.getAll('team_members');
    if (existing.length > 0) {
      console.log(`  [V7] team_members already has ${existing.length} records, skipping seed.`);
      return;
    }

    let inserted = 0;
    for (const m of SEED_MEMBERS) {
      const result = db.prepare('INSERT INTO team_members (team_id, name, role, phone, email) VALUES (?,?,?,?,?)')
        .run(m.team_id, m.name, m.role, m.phone, m.email);
      db.prepare('UPDATE teams SET members_count = (SELECT COUNT(*) FROM team_members WHERE team_id=?) WHERE id=?')
        .run(m.team_id, m.team_id);
      inserted++;
    }

    console.log(`  [V7] Seeded ${inserted} team_members.`);
  },
};
